FROM alpine:latest as builder

# Instalar ferramentas no builder
RUN apk add --no-cache aws-cli jq

# Imagem final
FROM prom/alertmanager:latest

USER root

# Copiar binários do builder
COPY --from=builder /usr/bin/aws /usr/bin/aws
COPY --from=builder /usr/bin/jq /usr/bin/jq
COPY --from=builder /usr/lib /usr/lib

USER nobody

ENTRYPOINT ["/entrypoint.sh"]
