-- Migrar dados de transactiondata para transactiondata_pos
-- Executar DEPOIS de adicionar as colunas faltantes

INSERT INTO transactiondata_pos (
    gateway,
    datahora,
    valor_original,
    celular,
    cpf,
    terminal,
    nsuHostCancellation,
    amountCancellation,
    originalAmount,
    preAuthorizationConfirmationTimestamp,
    amount,
    nsuTerminal,
    status,
    transactionWithSignature,
    nsuAcquirer,
    nsu_gateway,
    arqc,
    aid,
    terminalTimestamp,
    captureType,
    hostTimestampCancellation,
    authorizationCode,
    nsuHost,
    applicationName,
    brand,
    paymentMethod,
    totalInstallments,
    nsuTerminalCancellation,
    billPaymentEffectiveDate,
    pinCaptured,
    hostTimestamp,
    capturedTransaction,
    cardName,
    cardNumber,
    operador_pos,
    valor_desconto,
    valor_cashback,
    autorizacao_id,
    cashback_concedido,
    cupom_id,
    cupom_valor_desconto,
    modalidade_wall,
    created_at,
    updated_at
)
SELECT
    'PINBANK' as gateway,
    CASE
        WHEN datahora REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}' THEN
            STR_TO_DATE(SUBSTRING(datahora, 1, 19), '%Y-%m-%dT%H:%i:%s')
        WHEN datahora REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}' THEN
            STR_TO_DATE(datahora, '%Y-%m-%d %H:%i:%s')
        ELSE
            NOW()
    END as datahora,
    valor_original,
    celular,
    cpf,
    terminal,
    nsuHostCancellation,
    amountCancellation,
    originalAmount,
    preAuthorizationConfirmationTimestamp,
    amount,
    nsuTerminal,
    status,
    transactionWithSignature,
    nsuAcquirer,
    CAST(nsuPinbank AS CHAR) as nsu_gateway,
    arqc,
    aid,
    terminalTimestamp,
    captureType,
    hostTimestampCancellation,
    authorizationCode,
    CAST(nsuHost AS CHAR) as nsuHost,
    applicationName,
    brand,
    paymentMethod,
    totalInstallments,
    nsuTerminalCancellation,
    billPaymentEffectiveDate,
    pinCaptured,
    CAST(hostTimestamp AS CHAR) as hostTimestamp,
    capturedTransaction,
    cardName,
    cardNumber,
    operador_pos,
    valor_desconto,
    valor_cashback,
    autorizacao_id,
    cashback_concedido,
    cupom_id,
    cupom_valor_desconto,
    modalidade_wall,
    NOW() as created_at,
    NOW() as updated_at
FROM wclub.transactiondata
WHERE nsuPinbank IS NOT NULL
ORDER BY id;
